import type { User } from "./types"

export const sampleUsers: User[] = [
  {
    id: "1",
    name: "Alice Johnson",
    bio: "Passionate about web development and teaching",
    skillsOffering: ["React", "JavaScript", "CSS"],
    skillsLooking: ["Python", "Machine Learning", "Data Analysis"],
    experienceLevel: "Advanced",
    location: "Dhaka, Bangladesh",
    language: "Bangla",
    rating: 4.8,
  },
  {
    id: "2",
    name: "Bob Smith",
    bio: "Data scientist eager to learn frontend skills",
    skillsOffering: ["Python", "Machine Learning", "Data Analysis"],
    skillsLooking: ["React", "JavaScript", "CSS"],
    experienceLevel: "Advanced",
    location: "Dhaka, Bangladesh",
    language: " Bangla",
    rating: 4.6,
  },
  {
    id: "3",
    name: "Carol Davis",
    bio: "Beginner developer looking to grow",
    skillsOffering: ["HTML", "CSS", "Basic JavaScript"],
    skillsLooking: ["React", "Node.js", "Database Design"],
    experienceLevel: "Beginner",
    location: "Dhaka, Bangladesh",
    language: "Bangla",
    rating: 4.2,
  },
  {
    id: "4",
    name: "David Wilson",
    bio: "Full-stack developer and tech mentor",
    skillsOffering: ["Node.js", "Database Design", "System Architecture"],
    skillsLooking: ["Mobile Development", "DevOps", "Cloud Computing"],
    experienceLevel: "Advanced",
    location: "Seattle, USA",
    language: "English",
    rating: 4.9,
  },
  {
    id: "5",
    name: "Emma Brown",
    bio: "Mobile app developer interested in backend",
    skillsOffering: ["React Native", "Mobile Development", "UI/UX"],
    skillsLooking: ["Node.js", "Database Design", "API Development"],
    experienceLevel: "Intermediate",
    location: "Los Angeles, USA",
    language: "English",
    rating: 4.5,
  },
  {
    id: "6",
    name: "John Developer",
    bio: "Java expert looking to learn Python",
    skillsOffering: ["Java", "Spring Boot", "OOP Design"],
    skillsLooking: ["Python", "Django", "Data Science"],
    experienceLevel: "Advanced",
    location: "New York, USA",
    language: "English",
    rating: 4.7,
  },
  {
    id: "7",
    name: "Sarah Pythonista",
    bio: "Python specialist eager to master Java",
    skillsOffering: ["Python", "Django", "Data Science"],
    skillsLooking: ["Java", "Spring Boot", "OOP Design"],
    experienceLevel: "Advanced",
    location: "New York, USA",
    language: "English",
    rating: 4.8,
  },
  {
    id: "8",
    name: "Mike JavaScript",
    bio: "JavaScript expert looking to learn Python",
    skillsOffering: ["JavaScript", "TypeScript", "Node.js"],
    skillsLooking: ["Python", "Django", "Data Science"],
    experienceLevel: "Advanced",
    location: "New York, USA",
    language: "English",
    rating: 4.6,
  },
]
